
services:
  mongo_db:
    image: mongo:latest
    container_name: mongo_global
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - "${MONGO_LAN_IP}:${MONGO_PORT}:27017" # LAN only
    volumes:
      - mongo_data:/data/db
    networks:
      - mongonet

volumes:
  mongo_data:

networks:
  mongonet:
    driver: bridge
