services:
  studentsync-backend:
    image: vasujain275/studentsync-api:${VERSION:-latest}
    container_name: studentsync-backend
    restart: unless-stopped
    ports:
      - "9501:8080"
    env_file: .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - studentsync-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 60s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  studentsync-network:
    driver: bridge
